#Tell Gitlab to load these environental vars from the variables list
variables:
  PYPI_USER: SECURE
  PYPI_PASS: SECURE

stages:
  - build
  - test
  - deploy


build docs:
  stage: build
  script:
    - tox -e docs
  tags:
    - shared-linux
  artifacts:
    paths:
    - doc/
    expire_in: 1 week

test Linux:
  stage: test
  variables:
    DISPLAY: localhost:1
  script:
      - echo "DISPLAY=${DISPLAY}"
      - tox
  tags:
    - shared-linux, gui
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

test macOS:
  stage: test
  script:
      - tox
  tags:
    - shared-mac, gui

test Windows:
  stage: test
  script:
      - tox
  tags:
    - shared-win, gui
